allowCompoundWords: true
dictionaries:
  - cpp
enableGlobDot: true
features:
  weighted-suggestions: true
globRoot: ${cwd}
id: kurone-kito
language: en,ja
ignorePaths:
  - .*ignore
  - .git
  - .github/CODE_OF_CONDUCT.*
  - .vscode/extensions.json
  - cspell.config.yml
useGitignore: true
version: '0.2'
words:
  - kito
  - kuron√©
  - scriban
  - udonsharp
